#!/bin/zsh
# Regenerates lib/blur.ts: tiny base64 previews for every image in public/images
out=lib/blur.ts
echo "// Generated by raw/blur.sh. Tiny previews for the blur-up image load." > $out
echo "export const blur: Record<string, string> = {" >> $out
for f in $(find public/images -name '*.webp' | sort); do
  b=$(magick "$f" -resize 24x -quality 50 webp:- | base64 | tr -d '\n')
  echo "  \"/${f#public/}\": \"data:image/webp;base64,$b\"," >> $out
done
echo "};" >> $out
