import { at } from "@/lib/time";
import { makeTenant } from "../make";
import type { TenantData } from "../types";
import { images } from "./images";

/**
 * The Meridian: a fictional 1931 setback tower in Chicago's Loop, here to show the same product
 * running a second, different building. No fitness, a stepped silhouette, a lake-blue accent.
 */
const FLOORS = 44;

/** Setbacks at 18, 32 and 40, like a wedding cake */
const tiers: [from: number, w: number, d: number][] = [
  [0, 3.3, 2.5],
  [18, 2.7, 2.05],
  [32, 2.05, 1.6],
  [40, 1.35, 1.35],
];
const tierAt = (floor: number) => [...tiers].reverse().find(([from]) => floor >= from)!;

const data: TenantData = {
  id: "meridian",
  building: {
    name: "The Meridian",
    address: "300 West Meridian Plaza",
    city: "Chicago",
    floors: FLOORS,
    heightFt: 612,
    opened: 1931,
    operator: "Playbook",
    concierge: { phone: "(312) 555-0144", email: "desk@meridian.example", hours: "Weekdays 7am–8pm" },
    services: { spaces: true, fitness: false, programming: true },
    // No photography yet: the hero is the building's own 3D render
    hero: images.hallColonnade,
    heroTower: true,
  },
  theme: { accent: "#2c4f8c", deep: "#1f3b6c", soft: "#e1e7f3", glow: "#7fa4ea" },
  // A stepped setback tower with its lantern and mast
  mark: {
    paths: [
      { d: "M9.4 0 H10.6 V4 H12 V8 H13.6 V14 H15.4 V31 H4.6 V14 H6.4 V8 H8 V4 H9.4 Z" },
      { d: "M8.2 16 H9.2 V29 H8.2 Z M10.8 16 H11.8 V29 H10.8 Z", opacity: 0.45 },
    ],
  },
  tower: {
    floors: FLOORS,
    floorH: 0.2,
    widthAt: (f) => tierAt(f)[1],
    depthAt: (f) => tierAt(f)[2],
    crown: { kind: "lantern", height: 0.9, radius: 0.5, mast: 1.8 },
    facade: { slits: 22, width: 0.42 },
    // Meridian Plaza opens to the south
    park: { x: 0, z: 3.6, w: 3.6, d: 2.4, pad: [0.6, 0.6], trees: 14, shape: "round", yaw: [1.57, 0.8] },
    city: { inner: 3.6, count: 40 },
    restLevel: 40,
    seed: 7,
  },
  levels: [
    { n: 0, label: "Plaza", place: "Meridian Plaza", audience: "both" },
    { n: 1, label: "L1", place: "The Great Hall", href: "/venues/great-hall", audience: "both" },
    { n: 12, label: "L12", place: "Meeting rooms", href: "/spaces", audience: "member" },
    { n: 40, label: "L40", place: "The Lantern Room", href: "/venues/lantern-room", audience: "both" },
    { n: 44, label: "L44", place: "The mast", audience: "public" },
  ],
  people: [
    {
      id: "rosa",
      name: "Rosa Lindgren",
      role: "Events & hospitality lead",
      bio: "Rosa ran private events for two Loop hotels before the Meridian. She knows every caterer on Wacker by first name and will walk the room with you at the hour your event happens.",
      initials: "RL",
      since: "With the Meridian since 2023",
    },
    {
      id: "wes",
      name: "Wes Adeyemi",
      role: "Community programming",
      bio: "Books the architects, the record collectors and the Friday coffee.",
      initials: "WA",
    },
  ],
  leadId: "rosa",
  member: { first: "Priya", last: "Shah", email: "priya.shah@halvorsen.example", company: "Halvorsen Partners", floor: "Level 22" },
  venues: [
    {
      slug: "lantern-room",
      name: "The Lantern Room",
      level: 40,
      levelLabel: "Level 40",
      kind: "Crown lounge",
      tagline: "Forty floors up, inside the lit crown you can see from the lake.",
      summary:
        "The top setback of the tower: a walnut bar, deep armchairs and windows on all four sides. The lake to the east, the river below, the Loop switching on around you.",
      story: [
        "The Lantern Room was the building's observation deck in 1931. It's glassed in now, but the brass rails and the terrazzo compass in the floor are original.",
        "It holds a standing reception or a long seated dinner, and after dark the crown above it glows the building's blue.",
      ],
      capacities: { reception: 110, banquet: 60, lounge: 50 },
      sqft: 2800,
      features: [
        { icon: "view", label: "Four-way views", detail: "Lake Michigan, the river and the Loop" },
        { icon: "glass", label: "Walnut cocktail bar", detail: "Staffed bar service through approved caterers" },
        { icon: "music", label: "House sound", detail: "A quiet system tuned for conversation" },
        { icon: "moon", label: "Lit crown", detail: "The lantern above glows after sunset" },
        { icon: "access", label: "Step-free access", detail: "Express elevator from the Great Hall" },
      ],
      goodFor: ["Receptions", "Client dinners", "Launches", "Holiday parties"],
      tags: ["views", "evening", "catering", "private"],
      hero: images.lanternBar,
      gallery: [images.lanternBar, images.lanternLounge, images.lanternRound, images.lanternCoffee, images.talk],
      hostId: "rosa",
      plate: { w: 17, d: 15.3, windows: "wrap" },
    },
    {
      slug: "great-hall",
      name: "The Great Hall",
      level: 1,
      levelLabel: "Ground floor",
      kind: "Grand lobby hall",
      tagline: "A double-height deco hall at the foot of the tower, big enough for the whole building.",
      summary:
        "Coffered oak ceilings, sculpted columns and pale stone floors. By day it's the building's front door; after hours it sets for a town hall, a gala or a market.",
      story: [
        "The hall runs the full width of the tower between the plaza and the river walk, with tall windows at both ends.",
        "Evening events take the whole room from 6pm. Daytime events use the east half while the lobby stays open.",
      ],
      capacities: { reception: 260, theater: 180, banquet: 140, classroom: 90 },
      sqft: 6200,
      features: [
        { icon: "sun", label: "Double-height daylight", detail: "Tall windows at both ends of the hall" },
        { icon: "screen", label: "Projection and screen", detail: "A drop-down screen and 4K projector" },
        { icon: "mic", label: "Wireless mics", detail: "Four handhelds and a lectern" },
        { icon: "coffee", label: "Coffee bar next door", detail: "Espresso service for day events" },
        { icon: "people", label: "Staffed setup", detail: "Our team sets and turns the room" },
      ],
      goodFor: ["Town halls", "Galas", "Conferences", "Markets"],
      tags: ["daylight", "av", "catering"],
      hero: images.hallColonnade,
      gallery: [images.hallColonnade, images.hallTheater, images.hallLounge, images.hallDesk, images.hallCoffee],
      hostId: "rosa",
      plate: { w: 32, d: 18, windows: "north" },
    },
  ],
  venueTags: [
    { id: "views", label: "Lake views" },
    { id: "evening", label: "Evening events" },
    { id: "daylight", label: "Daylight" },
    { id: "catering", label: "Catering-ready" },
    { id: "av", label: "Full AV" },
    { id: "private", label: "Fully private" },
  ],
  rooms: [
    {
      slug: "wacker",
      name: "Wacker",
      namesake: "Wacker Drive, along the river",
      level: 12,
      capacity: 5,
      setups: ["boardroom"],
      summary: "A small corner room over the river for one-on-ones and interviews.",
      amenities: [
        { icon: "view", label: "River views" },
        { icon: "screen", label: "43-inch display" },
        { icon: "whiteboard", label: "Wall whiteboard" },
      ],
      image: images.huddle,
      approval: "instant",
      tags: ["small", "views", "whiteboard"],
      plate: { w: 6, d: 5, windows: "east" },
    },
    {
      slug: "lasalle",
      name: "LaSalle",
      namesake: "LaSalle Street, the old financial canyon",
      level: 12,
      capacity: 10,
      setups: ["boardroom", "classroom"],
      summary: "Ten seats around a walnut table, with a camera and mics for hybrid meetings.",
      amenities: [
        { icon: "video", label: "Video-call kit", detail: "Camera, mics and one-touch join" },
        { icon: "screen", label: "75-inch display" },
        { icon: "coffee", label: "Coffee credenza" },
      ],
      image: images.boardroom,
      approval: "instant",
      tags: ["video", "views"],
      plate: { w: 10, d: 6, windows: "north" },
    },
    {
      slug: "randolph",
      name: "Randolph",
      namesake: "Randolph Street and the old theater district",
      level: 12,
      capacity: 30,
      setups: ["boardroom", "theater", "classroom", "reception"],
      summary: "The floor's big room for workshops and all-hands. Needs a quick approval from the events team.",
      amenities: [
        { icon: "screen", label: "Dual displays" },
        { icon: "mic", label: "Room mics" },
        { icon: "people", label: "Staffed setup" },
      ],
      image: images.boardroomReal,
      approval: "request",
      tags: ["large", "video"],
      plate: { w: 13, d: 9, windows: "north" },
    },
  ],
  roomTags: [
    { id: "small", label: "Up to 6" },
    { id: "large", label: "12+" },
    { id: "views", label: "River views" },
    { id: "video", label: "Video calls" },
  ],
  fitness: null,
  events: () => [
    {
      slug: "deco-on-foot",
      name: "Deco on foot: a Loop walk",
      kicker: "Architecture",
      startsAt: at(1, 12 * 60 + 15),
      durationMin: 45,
      place: "Meridian Plaza",
      level: 0,
      summary: "A lunchtime walk past five 1930s towers with an architecture center docent, starting under our own setbacks.",
      body: [
        "Forty-five minutes, five buildings, one question: why did Chicago's skyscrapers start stepping back in the '20s? Our docent answers it on the sidewalk.",
        "Back in time for a 1pm meeting. Comfortable shoes recommended.",
      ],
      capacity: 20,
      going: 20,
      access: { type: "all" },
      hostId: "wes",
      image: images.hallColonnade,
      tone: "day",
    },
    {
      slug: "halvorsen-autumn",
      name: "Halvorsen autumn social",
      kicker: "Company gathering",
      startsAt: at(2, 17 * 60),
      durationMin: 120,
      place: "The Lantern Room",
      level: 40,
      summary: "Drinks at the top of the tower for the Halvorsen Partners team, hosted with the building.",
      body: ["An end-of-season get-together for Halvorsen's floors. Bring someone you haven't met yet."],
      capacity: 90,
      going: 47,
      access: { type: "company", company: "Halvorsen Partners" },
      hostId: "wes",
      image: images.lanternLounge,
      tone: "night",
    },
    {
      slug: "listening-session",
      name: "Lantern Room listening session",
      kicker: "Music",
      startsAt: at(3, 17 * 60 + 30),
      durationMin: 90,
      place: "The Lantern Room",
      level: 40,
      summary: "A Chicago record collector plays a side of Blue Note on the house system while the city lights up.",
      body: ["One album, start to finish, no phones. Then drinks and conversation at the bar as the crown comes on above you."],
      capacity: 40,
      going: 31,
      access: { type: "all" },
      hostId: "wes",
      image: images.lanternRound,
      tone: "night",
    },
    {
      slug: "friday-coffee",
      name: "Friday coffee in the hall",
      kicker: "Coffee",
      startsAt: at(4, 8 * 60 + 30),
      durationMin: 60,
      place: "The Great Hall",
      level: 1,
      summary: "A local roaster pours three coffees at a pop-up bar by the east windows. Drop by on your way up.",
      body: ["No RSVP needed to stop by, but an RSVP saves you a bag of beans to take upstairs."],
      capacity: 120,
      going: 64,
      access: { type: "all" },
      hostId: "wes",
      image: images.cupping,
      tone: "day",
    },
  ],
  copy: {
    the: "the Meridian",
    The: "The Meridian",
    weather: "Wind off the lake · 58°F",
    concierge: "L1, under the clock in the Great Hall",
    memberHero: { img: images.hallColonnade, lines: ["Everything the", "Meridian has,", "in one place."] },
    signInImg: images.hallCoffee,
    pitches: {
      spaces: {
        title: "A room when you need one. A team when it's bigger.",
        body: "Book one of three rooms on L12 in seconds, or hand a gala or town hall to our events team.",
        points: ["Three rooms for 5 to 30", "Instant booking for most", "Event planning with Rosa"],
        img: images.boardroom,
        cta: "Explore spaces",
        access: "Included with your building access",
      },
      events: {
        title: "Reasons to look up from your desk.",
        body: "Architecture walks, listening sessions at the top of the tower and Friday coffee in the hall.",
        points: ["Something most weeks", "RSVP in one tap", "Some just for your company"],
        img: images.lanternRound,
        cta: "See what's on",
        access: "Included with your building access",
      },
    },
    firstWeek: {
      room: { d: "Three rooms on L12. Wacker has the best view of the river.", img: images.huddle },
      event: { d: "The Loop walk is a great first one.", img: images.hallColonnade },
      concierge: { img: images.hallDesk },
    },
    spaces: { roomsImg: images.boardroomReal, planImg: images.lanternRound, planHero: images.lanternLounge },
    programmingLead: "Architecture walks, records at the top of the tower and Friday coffee",
    kickers: { Architecture: "Architecture", Music: "Music", Coffee: "Food & drink" },
    usuals: [
      { id: "lasalle", label: "LaSalle room", icon: "spaces", href: "/spaces/lasalle" },
      { id: "wacker", label: "Wacker room", icon: "spaces", href: "/spaces/wacker" },
    ],
    seed: { room: "lasalle", event: "listening-session" },
    policies: [
      { icon: "clock", t: "Evening events end by midnight", d: "Load-in from 3pm on event days, through the river-walk dock." },
      { icon: "glass", t: "Approved caterers", d: "Five partner caterers, or bring your own with a kitchen fee." },
      { icon: "shield", t: "Holds and deposits", d: "We hold a date for 10 days while you decide. A deposit confirms it." },
      { icon: "calendar", t: "Changes and cancellation", d: "Full refund up to 45 days out; 50% up to 21 days." },
    ],
    public: {
      title: "Gather at the Meridian",
      description: "Host your gala, town hall or dinner at the Meridian in Chicago: the Lantern Room on L40 and the Great Hall.",
      heroLines: ["Gather at", "the Meridian."],
      heroLead:
        "From a deco hall at the foot of the tower to a lounge inside its lit crown, host the night people remember, with a team that does this every week.",
      collection: ["Two rooms to gather in,", "from the Great Hall to the 40th floor."],
      hostQuote: "Give me the date and the mood. I'll handle the room, the caterer and the elevator.",
      moments: [
        { img: images.lanternLounge, title: "A partners' dinner for forty", where: "The Lantern Room" },
        { img: images.hallTheater, title: "A town hall for 180", where: "The Great Hall" },
        { img: images.lanternRound, title: "Records at blue hour", where: "The Lantern Room" },
        { img: images.hallLounge, title: "A winter market", where: "The Great Hall" },
      ],
      around: [
        { img: images.hallCoffee, t: "Coffee in the hall", d: "A stone espresso bar by the east windows, open to your guests." },
        { img: images.hallDesk, t: "The concierge desk", d: "Guests check in under the coffered ceiling and ride straight up." },
        { img: images.archive, t: "The 1931 archive", d: "Construction photographs from the year the tower went up, on the mezzanine." },
      ],
      aroundLead: "The building does half the hosting, from the deco hall to the archive on the mezzanine.",
      gettingHere: [
        { k: "Address", v: "300 West Meridian Plaza, Chicago", d: "On the river, between the Loop and the West Loop." },
        { k: "Transit", v: "4 minutes from Clark/Lake", d: "Every L line but one, and the Metra at Ogilvie a short walk west." },
        { k: "Arrivals", v: "Guest check-in in the Great Hall", d: "Our team meets your guests at the desk and rides up with them." },
        { k: "By water", v: "Water taxi to the river walk", d: "Guests can arrive by boat in season and walk straight into the hall." },
      ],
      towerPoster: images.hallColonnade,
      floorIntro: {
        title: "612 feet. 44 floors. Two rooms to gather in.",
        body: "Scroll up the setbacks. The hall sits at the foot of the tower and the Lantern Room at the top.",
      },
      crown: {
        level: 44,
        readout: "The mast",
        title: "And above it, the mast.",
        body: "A 1931 mooring mast that never moored anything. It's lit blue every night and you can see it from the lake.",
      },
    },
  },
};

export const meridian = makeTenant(data);
