import type { Amenity } from "@/lib/data/types";
import { images } from "./images";
import { venues } from "./venues";

/**
 * What someone who works in the Pyramid can use. None of this has been confirmed by the building yet:
 * floors and details come from its own site and press since the 2024 reopening, and some sources disagree.
 * `confirmed` flips per item as TAP answers; the open questions are in docs/member-experience.md.
 */

const hero = (slug: string) => venues.find((v) => v.slug === slug)?.hero;

const PRESS = "Time Out SF and Haute Living, 2024–25";

export const amenities: Amenity[] = [
  {
    id: "wellness",
    name: "The wellness center",
    group: "move",
    level: 26,
    where: "Level 26",
    access: "membership",
    blurb: "A gym whose machines face the slanted windows, a yoga studio with classes, and steam and sauna before you head back up.",
    points: ["Coached classes", "Yoga studio", "Steam and sauna", "Changing rooms"],
    img: images.gym,
    href: "/fitness",
    cta: "See classes",
    confirmed: false,
    source: PRESS,
  },
  {
    id: "sky-lounge",
    name: "Sky Lounge",
    group: "work",
    level: 27,
    where: "Level 27",
    access: "included",
    blurb: "A work lounge and espresso bar with the window framed on Coit Tower. Bring a laptop, stay for the view.",
    points: ["Espresso bar", "Work tables and sofas", "Bridge-to-bridge views"],
    img: images.bayCoit,
    confirmed: false,
    source: `${PRESS}. It may be the tenant name for Bay Lounge.`,
  },
  {
    id: "meeting-rooms",
    name: "Meeting rooms",
    group: "meet",
    level: 6,
    where: "Level 6",
    access: "included",
    blurb: "Rooms named for the tower's architects and streets, from a four-seat huddle to the Foster Room. Most book instantly.",
    img: images.boardroomReal,
    href: "/spaces",
    cta: "Book a room",
    confirmed: false,
    source: "Foster and Pereira from Core staging; floor not confirmed",
  },
  {
    id: "event-venues",
    name: "Event venues",
    group: "meet",
    level: null,
    where: "Five venues, Level 3 to Level 48",
    access: "request",
    blurb: "When it's bigger than a meeting: The Sandbox, Bay Lounge, Legacy Gallery, Sky Bar and the park, planned with the events team.",
    img: hero("bay-lounge"),
    href: "/spaces/plan-an-event",
    cta: "Plan an event",
    confirmed: true,
    source: "Transamerica Pyramid booklet",
  },
  {
    id: "sky-bar",
    name: "Sky Bar",
    group: "gather",
    level: 48,
    where: "Level 48, the top floor",
    access: "included",
    blurb: "The tenant cocktail lounge at the top of the tower, with food by Brad Kilgore and the whole city below.",
    img: hero("sky-bar"),
    confirmed: false,
    source: "SF Standard, Aug 2024 (opening hours and tenant access not confirmed)",
  },
  {
    id: "lobby",
    name: "Lobby coffee bar",
    group: "eat",
    level: 1,
    where: "Level 1, the lobby",
    access: "public",
    blurb: "Espresso at the stone bar under the oak ceiling, with flowers and books for sale on the way out.",
    img: images.lobbyCoffee,
    confirmed: false,
    source: "transamericapyramid.com photography; Archinect, Sept 2024",
  },
  {
    id: "dining",
    name: "Dining on the block",
    group: "eat",
    level: null,
    where: "Transamerica Three, Mark Twain Alley",
    access: "public",
    blurb: "Breakfast and lunch at Café Sebastian under the trees, gelato and kakigori at MadLab, and dinner and records at Ama.",
    points: ["Café Sebastian", "MadLab Gelato & Kakigori", "Ama by Brad Kilgore"],
    confirmed: false,
    source: "SF Standard, Aug 2024",
  },
  {
    id: "park",
    name: "Transamerica Redwood Park",
    group: "gather",
    level: 0,
    where: "At the foot of the tower",
    access: "public",
    blurb: "Half an acre of redwoods brought from the Santa Cruz Mountains, with free concerts in the grove through the warmer months.",
    img: images.redwoodFountain,
    href: "/programming",
    cta: "See what's on",
    confirmed: true,
    source: "transamericapyramid.com; the Pyramid Grove concert series",
  },
  {
    id: "arts",
    name: "Pyramid Arts",
    group: "gather",
    level: null,
    where: "Transamerica Two, second floor",
    access: "public",
    blurb: "A gallery on the block with a new exhibition about twice a year.",
    img: images.artStratagems,
    confirmed: false,
    source: PRESS,
  },
];
