import { at } from "@/lib/time";
import { images } from "./images";
import type { BuildingEvent } from "@/lib/data/types";

/** Built lazily so dates are relative to "now" in the browser. */
export const events = (): BuildingEvent[] => [
  {
    slug: "coffee-cupping",
    name: "Morning cupping with Andytown",
    kicker: "Coffee",
    startsAt: at(1, 9 * 60),
    durationMin: 45,
    place: "Bay Lounge",
    level: 27,
    summary: "Taste four single origins side by side with a local roaster, and learn what to look for in your next bag.",
    body: [
      "Cupping is how roasters taste: no milk, no sugar, a spoon and a lot of slurping. We'll set up four coffees on the walnut bar and walk through them together.",
      "Seats are limited to keep it hands-on. Take a bag of your favorite home with you.",
    ],
    capacity: 24,
    going: 24,
    access: { type: "all" },
    hostId: "theo",
    image: images.cupping,
    tone: "day",
  },
  {
    slug: "northline-quarterly",
    name: "Northline quarterly social",
    kicker: "Company gathering",
    startsAt: at(2, 16 * 60 + 30),
    durationMin: 120,
    place: "Bay Lounge",
    level: 27,
    summary: "Drinks and small plates for the Northline Capital team, hosted with the building.",
    body: ["An end-of-quarter get-together for Northline's floors. Bring a colleague from another team."],
    capacity: 80,
    going: 41,
    access: { type: "company", company: "Northline Capital" },
    hostId: "theo",
    image: images.bayReception,
    tone: "night",
  },
  {
    slug: "the-pyramid-at-54",
    name: "The Pyramid at 54",
    kicker: "Speaker series",
    startsAt: at(6, 17 * 60 + 30),
    durationMin: 75,
    place: "Bay Lounge",
    level: 27,
    summary: "An architectural historian on how a controversial 1972 tower became the city's favorite silhouette.",
    body: [
      "When it was proposed, critics called it a dunce cap. Half a century on, it's on the city's postcards. Our guest walks through the design, the fights over it, and the redwoods at its feet.",
      "Q&A and drinks afterward, with the bay going blue behind us.",
    ],
    capacity: 90,
    going: 58,
    access: { type: "all" },
    hostId: "theo",
    image: images.historyGallery,
    tone: "night",
  },
  {
    slug: "art-after-hours",
    name: "Art after hours: Stratagems",
    kicker: "Pyramid Arts",
    startsAt: at(3, 17 * 60 + 30),
    durationMin: 60,
    place: "The Pavilion",
    level: 1,
    summary: "A curator-led walk through Tara Donovan's sculptures in the glass pavilion, with a glass of wine in hand.",
    body: [
      "Stratagems fills the pavilion with towering, twisting columns built from thousands of identical parts. Up close they read as texture; from across the room, as architecture.",
      "Our curator walks the installation with you for forty minutes, then the pavilion stays open for drinks.",
    ],
    capacity: 40,
    going: 26,
    access: { type: "all" },
    hostId: "theo",
    image: images.artStratagems,
    tone: "day",
  },
  {
    slug: "evening-in-the-grove",
    name: "An evening in the grove",
    kicker: "Music",
    startsAt: at(8, 17 * 60),
    durationMin: 120,
    place: "Redwood Park",
    level: 0,
    summary: "A jazz trio under the redwoods, a wine cart and the whole building invited.",
    body: ["We're reviving the park's old summer sets for one more evening before the fog season. Bring a jacket and a coworker."],
    capacity: 200,
    going: 112,
    access: { type: "all" },
    hostId: "theo",
    image: images.redwoodEvening,
    tone: "night",
  },
  {
    slug: "chefs-table-preview",
    name: "Chef's table preview",
    kicker: "Members' preview",
    startsAt: at(12, 18 * 60),
    durationMin: 90,
    place: "Bay Lounge",
    level: 27,
    summary: "A seated tasting of the lounge's new autumn menu, for a small invited group.",
    body: ["Twelve seats at one table. Invitations go to building VIP list members; ask the concierge if you'd like to be considered for the next one."],
    capacity: 12,
    going: 9,
    access: { type: "vip" },
    hostId: "ines",
    image: images.clubBar,
    tone: "day",
  },
];
